In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40])

print(arr + 5)
print(arr * 2)
print(np.mean(arr))
print(np.std(arr))


[15 25 35 45]
[20 40 60 80]
25.0
11.180339887498949


In [2]:
precos = np.array([10, 20, 30])
ajuste = 1.1
print(precos * ajuste)

[11. 22. 33.]


In [ ]:
import pandas as pd
import numpy as np

df  = pd.DataFrame({
	'produto': ['Notebook', 'Mouse','Monitor' ,  'teclado'],
	'preco': [4500.1111, 150.2222, 1500.2222,320.2222313]
})
df['preco_ajustado'] = np.round(df['preco'] * 1.10, 2) # arredondamento para 2 casas decimais
display(df['preco_ajustado'])

# Operação acontece para todos os itens de preço sem a necessidade de loop
df['preco_ajustado'] = (df['preco'] - np.mean(df['preco'])) - np.std(df['preco']) #escalonamento de dados

# Normalização são usadas para graficos e para estatisticas
df['preco_normalizado_z'] = (df['preco'] - np.mean(df['preco'])) / np.std(df['preco'])

print(df)
print(df['preco_normalizado_z'].mean())
print(df['preco_normalizado_z'].std())



0    4950.12
1     165.24
2    1650.24
3     352.24
Name: preco_ajustado, dtype: float64

    produto        preco  preco_ajustado  preco_normalizado_z
0  Notebook  4500.111100     1138.926315             1.653245
1     Mouse   150.222200    -3210.962585            -0.841686
2   Monitor  1500.222200    -1860.962585            -0.067378
3   teclado   320.222231    -3040.962554            -0.744181
-8.326672684688674e-17
1.1547005383792515


In [4]:
df['preco'] = df['preco'] * 1.01

display(df)

,produto,preco,preco_ajustado
0,Notebook,4545.112211,831.573827
1,Mouse,151.724422,-3518.315073
2,teclado,323.424454,-3348.315042
